######################################
# Author Matthew Aitchison
# Date: 20/Dec/2017
######################################
#
# Script to evaluate the performance of the classifier.
#
# Runs through a folder containing the output stats file generated by the classifer and checks how often it was correct.
# For this to work the input CPTV files must have had a ".dat" file along side them that contains the pre-tagged tagging
# information.
#
# CPTV files are clustered into visits under the following rules:
#
#     If two clips are more than 3 minutes apart start a new visit
#     If two clips differ on tag start a new visit
#
# CPTV files with two or more different tags are excluded from analysis.
#

"""
Information required in stats file
source
camera
start time + end time
original tags
track information:
    start + end time
    label
    confidence
    clarity

"""

# number of seconds between clips required to trigger a a new visit
NEW_VISIT_THRESHOLD = 3*60

